//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomskiISpoljoprivreda
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrojParcele
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BrojParcele()
        {
            this.Klijent = new HashSet<Klijent>();
            this.Mjesto = new HashSet<Mjesto>();
        }
    
        public int ParcelaID { get; set; }
        public string BrojParcele1 { get; set; }
        public string Opis { get; set; }
        public string Kvadratura { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Klijent> Klijent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mjesto> Mjesto { get; set; }
    }
}
