//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomskiISpoljoprivreda
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finansije
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Finansije()
        {
            this.Izvjestaj = new HashSet<Izvjestaj>();
        }
    
        public int FinansijeID { get; set; }
        public Nullable<decimal> Prihodi { get; set; }
        public Nullable<decimal> Rashodi { get; set; }
        public Nullable<decimal> FinansijskiRezultat { get; set; }
        public string Godina { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izvjestaj> Izvjestaj { get; set; }
    }
}
