//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomskiISpoljoprivreda
{
    using System;
    using System.Collections.Generic;
    
    public partial class Izvjestaj
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Izvjestaj()
        {
            this.Korisnik = new HashSet<Korisnik>();
        }
    
        public int IzvjestajID { get; set; }
        public int KategorijaID { get; set; }
        public int FinansijeID { get; set; }
        public int MjestoID { get; set; }
        public string Tip { get; set; }
        public string Opis { get; set; }
    
        public virtual Finansije Finansije { get; set; }
        public virtual Kategorija Kategorija { get; set; }
        public virtual Mjesto Mjesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Korisnik> Korisnik { get; set; }
    }
}
