//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomskiISpoljoprivreda
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termini
    {
        public int TerminID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Mail { get; set; }
        public string Telefon { get; set; }
        public string Svrha { get; set; }
        public string Opis { get; set; }
        public int KorisnikID { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
    }
}
